[project]
name = "space-invaders"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "imageio>=2.37.0",
    "numpy>=2.2.6",
    "pillow>=11.2.1",
    "pygame>=2.6.1",
    "torch>=2.7.0",
]
